import Head from 'next/head';
import {useEffect, useState} from "react";
import {getOffices} from "../../services/offices.service";
import CreateOffice from "../../components/offices/CreateOffice";

//import CreateUser from "../../components/users/CreateUser";


export default function Offices() {
    const [offices, setOffices] = useState<any[]>([]);
    useEffect(() => {
        getOffices().then(res => {
            setOffices(res.data)

        })

    }, [] )


    return (
        <div>
            <Head>
                <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
        </Head>
            <CreateOffice />
            {
                JSON.stringify(offices)
            }

    </div>
)
}
