import Head from 'next/head';
import {useEffect, useState} from "react";
import {getSubscriptions} from "../../services/subscriptions";
import CreateSubscription from "../../components/subscriptions/CreateSubscription";




export default function Products() {
    const [subscriptions, setSubscriptions] = useState<any[]>([]);
    useEffect(() => {
        getSubscriptions().then(res => {
            setSubscriptions(res.data)

        })

    }, [] )


    return (
        <div>
            <Head>
                <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
        </Head>
<CreateSubscription />
             {
                JSON.stringify(subscriptions)
            }

    </div>
)
}
