import Head from 'next/head';
import {useEffect, useState} from "react";
import {getProducts} from "../../services/products.service";
import CreateProduct from "../../components/products/CreateProduct";


//import CreateUser from "../../components/users/CreateUser";


export default function Products() {
    const [products, setProducts] = useState<any[]>([]);
    useEffect(() => {
        getProducts().then(res => {
            setProducts(res.data)

        })

    }, [] )


    return (
        <div>
            <Head>
                <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
        </Head>
 <CreateProduct />
             {
                JSON.stringify(products)
            }

    </div>
)
}
