import Head from 'next/head';
import {useEffect, useState} from "react";
import {getUsers} from "../../services/users.service";
import CreateUser from "../../components/users/CreateUser";


export default function Users() {
    const [users, setUsers] = useState<any[]>([]);
    useEffect(() => {
        getUsers().then(res => {
            setUsers(res.data)
            console.log(res)
        })

    }, [] )


    return (
        <div>
            <Head>
                <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
        </Head>
            <CreateUser />


    </div>
)
}
